# Generated by Django 4.2 on 2023-05-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='describe',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
